export const HOUSE_CHARACTERS_UPDATE_LOADING =
  'HOUSE_CHARACTERS_UPDATE_LOADING';
export const HOUSE_CHARACTERS_UPDATE_LIST = 'HOUSE_CHARACTERS_UPDATE_LIST';
export const HOUSE_CHARACTERS_UPDATE_ITEM = 'HOUSE_CHARACTERS_UPDATE_ITEM';
